//store.js
const Store = Vue.reactive({
  leadHeaders: [
    { title: "ID", align: "start", key: "id" },
    { title: "ชื่อลูกค้า", align: "start", key: "customerName" },
    { title: "สถานะ", align: "start", key: "status" },
    { title: "เบอร์ติดต่อ", align: "start", key: "contactNo" },
    { title: "รถยนต์", align: "start", key: "vehicle" },
    { title: "วันที่สร้าง", align: "start", key: "dateCreated" },
    { title: "จัดการ", align: "center", key: "actions", sortable: false },
  ],
  leadItems: [
    {
      id: 1,
      customerName: "John Doe",
      status: "Active",
      contactNo: "123-456-7890",
      vehicle: "Toyota Camry",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
    {
      id: 2,
      customerName: "Jane Smith",
      status: "Inactive",
      contactNo: "987-654-3210",
      vehicle: "Honda Civic",
    },
  ],
});
